### ISSUE TITLE
`robot_description` not published

### ISSUE THREAD

**Issue by Myzhar** [ros2/robot_state_publisher#14]
Using `robot_state_publisher` and `Rviz2` I noticed that the Robot Model is not loaded, so I checked and I figured out that the topic `robot_description` is empty.

See https://answers.ros.org/question/304645/ros2-robot-state-publisher-publishes-empty-robot_description/

**Comment by Karsten1987** [comment]
~~as mentioned on discourse, I would prefer not having the robot description published as a topic. Now with parameters being available, I think this topic should be replaced by a parameter and the respective RViz plugin updated accordingly. 
As there are no global parameters in ROS 2, I could imagine having the parameter attached to the robot state publisher node.~~

After revisiting https://github.com/ros2/robot_state_publisher/pull/9 and https://github.com/ros-visualization/rviz/issues/1125#issuecomment-325860303, it looks to me as if the publishing of the robot description was integrated delibrately. Reasons for that being a instant reaction of changes to this topic and the availability to record it.
Given that this publishing doesn't work as for now, this topic title makes sense.

**Comment by Karsten1987** [comment]
looking at the code, I think the robot state publisher publishes exactly once the robot description:
https://github.com/ros2/robot_state_publisher/blob/ros2/src/robot_state_publisher.cpp#L148-L152

Could you try to load RViz first and then start the robot state publisher? Or try to see this message via `ros2 topic echo` ?

**Comment by Myzhar** [comment]
@Karsten1987 I tried what you requested in the last comment and the topic is always empty... QOS policy compatibility?

**Comment by abylikhsanov** [comment]
So what is the situation with visualising the robot model in rviz2? I am getting no messages via robot description topic.

**Comment by Karsten1987** [comment]
@Myzhar I believe you're right and the topic QoS settings are incompatible. The robot state publisher publishes the topic in a latched fashion but RViz2 subscribes to it with the default QoS settings which are AFAIK incompatible.

I wonder now if this is a problem at the robot state publisher or RViz. It kind of makes sense to me to refactor RViz rather than the robot state publisher.
One way to try to solve this problem is to set the QoS profile in the robot model display correctly:
https://github.com/ros2/rviz/blob/ros2/rviz_common/include/rviz_common/ros_topic_display.hpp#L84

I haven't had much time to really look into this, but I believe that could be it.

@bponsler You were authoring the [PR](https://github.com/ros2/robot_state_publisher/pull/9). How did you test this functionality in RViz?

**Comment by Myzhar** [comment]
@karsten1987 I think you are right about the fact that this topic must be latched, so is Rviz that must be changed according to this setting :+1:

**Comment by bponsler** [comment]
@Karsten1987 I was testing with an initial branch of rviz which I had ported to work for ros2 (see: https://github.com/bponsler/rviz/tree/ros2-devel).

You can see in this commit where I modified the robot model display to subscribe to the published model: https://github.com/bponsler/rviz/commit/84b3b7d84a7d9ffd7a796976208169431c7728ee

Which was basically:

    rmw_qos_profile_t qos = rmw_qos_profile_default;
    qos.depth = 1;
    qos.durability = RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL;

    description_sub_ = update_nh_->create_subscription<std_msgs::msg::String>(
    topic,
    std::bind(&RobotModelDisplay::onDescription, this, std::placeholders::_1),
    qos);

**Comment by Karsten1987** [comment]
The referenced PR for RViz should fix the problem described here.  With that fix, if I start the `dummy_robot_bringup` the robot model is correctly displayed when subscribing to the topic `/robot_description`. I would appreciate if you could checkout that PR and give feedback on it.
