### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by samiamlabs** [ros2/robot_state_publisher#16]
Hi,

I'm getting a symbol lookup error when trying to run the robot_state_publisher node on the nightly build.

```
[INFO] [launch]: process[robot_state_publisher-1]: started with pid [1868]
/opt/ros/crystal/lib/robot_state_publisher/robot_state_publisher: symbol lookup error: /opt/ros/crystal/lib/robot_state_publisher/robot_state_publisher: undefined symbol: _ZN6rclcpp4NodeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11NodeOptionsE
```

I suspect that this relates to ros2/rclcpp#492 and the recent merge that adds support for NodeOptions.
Got it working on my fork by using `rcutils_cli_get_option` instaid of reading argv[1] directly.
This change requires the command line options to be `-f filename` instead of just `filename`, so will cause existing launch files to stop working.
(https://github.com/DynoRobotics/robot_state_publisher/tree/command-line-options)

**Comment by samiamlabs** [comment]
It seems my issue had to do with the sourcing of multiple workspaces in the Dockerfile I was using, not the command line option parsing.

I do think it is a good idea to use `rcutils_cli_get_option` for command line arguments but perhaps not worth breaking existing launch files?

**Comment by clalancette** [comment]
No, you are correct, we should properly handle command-line arguments by calling https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/utilities.hpp#L110, then looking for the argument in the "rest" of the list.

If you'd like to submit a PR to add this functionality, that would be great.  Otherwise, I'm going to do some refactoring of robot_state_publisher in the not-too-distant future, so I'll do it then.

**Comment by clalancette** [comment]
Superseded by https://github.com/ros/robot_state_publisher/issues/118, so closing.
