### ISSUE TITLE
Support for multiple instances of the same robot

### ISSUE THREAD

**Issue by deitry** [ros2/robot_state_publisher#35]
If `tf_prefix` is totally [deprecated](https://github.com/ros2/robot_state_publisher/pull/34#issuecomment-538357315), there _should_ be any other way to provide transforms for multiple instances of the same robot. In that case all `frame_id` are the same and usage of prefix was the simplest yet powerful way to deal with that.

`sed`ing and `xacro`ing URDF before passing to `robot_state_publisher` in order to provide unique names for each link feels very 'manual' and excessive. Alternative way would be to prefix frame ids with actual publisher node namespace - which is actually the same approach as usage of `tf_prefix` but with more implicit configuration.

I do not understand your position on `tf_prefix` prohibition without providing anything instead.

**Comment by clalancette** [comment]
> I do not understand your position on `tf_prefix` prohibition without providing anything instead.

So I think that link lays out the reasons for it being deprecated pretty well; namely, that the ecosystem never coalesced around it very well, and hence it didn't really work properly.

One solution that we have done for this problem is to publish on namespaced `tf` and `tf_static` topics, and then use a node to bridge transforms to the global `/tf` and `/tf_static` topics with prefixed frame names.  We don't have a default package that does that, but there is a good example of it working in ROS 1 here: https://bitbucket.org/osrf/ariac/src/master/osrf_gear/src/tf2_relay.cpp

**Comment by deitry** [comment]
Thank you very much for providing this information, it wasn't clear from tf2/Migration article.

**Comment by clalancette** [comment]
> Thank you very much for providing this information, it wasn't clear from tf2/Migration article.

You are welcome, let us know how it works out for you.

**Comment by clalancette** [comment]
I'm actually going to close this out, as we are deprecating this repository to merge the code back into https://github.com/ros/robot_state_publisher.  If you still feel like you need another solution here, feel free to open a new issue over there.  Thanks.
